// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Purchase Cart API
 *
 * Purchase Cart API is an API to create an order with items and get the pricing information for the order
 *
 * API version: 1.0
 */

package api

import (
	"context"
	"net/http"
)

// PurchaseCartAPIRouter defines the required methods for binding the api requests to a responses for the PurchaseCartAPI
// The PurchaseCartAPIRouter implementation should parse necessary information from the http request,
// pass the data to a PurchaseCartAPIServicer to perform the required actions, then write the service results to the http response.
type PurchaseCartAPIRouter interface {
	V1OrderPost(http.ResponseWriter, *http.Request)
}

// PurchaseCartAPIServicer defines the api actions for the PurchaseCartAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type PurchaseCartAPIServicer interface {
	V1OrderPost(context.Context, CreateOrderRequest) (ImplResponse, error)
}
