// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Purchase Cart API
 *
 * Purchase Cart API is an API to create an order with items and get the pricing information for the order
 *
 * API version: 1.0
 */

package api

// ImplResponse defines an implementation response with error code and the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}
