// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Purchase Cart API
 *
 * Purchase Cart API is an API to create an order with items and get the pricing information for the order
 *
 * API version: 1.0
 */

package api

// CreateOrderRequest - The request to create an order
type CreateOrderRequest struct {
	Order CreateOrderRequestOrder `json:"order"`
}

// AssertCreateOrderRequestRequired checks if the required fields are not zero-ed
func AssertCreateOrderRequestRequired(obj CreateOrderRequest) error {
	elements := map[string]interface{}{
		"order": obj.Order,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertCreateOrderRequestOrderRequired(obj.Order); err != nil {
		return err
	}
	return nil
}

// AssertCreateOrderRequestConstraints checks if the values respects the defined constraints
func AssertCreateOrderRequestConstraints(obj CreateOrderRequest) error {
	if err := AssertCreateOrderRequestOrderConstraints(obj.Order); err != nil {
		return err
	}
	return nil
}
