// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Purchase Cart API
 *
 * Purchase Cart API is an API to create an order with items and get the pricing information for the order
 *
 * API version: 1.0
 */

package api

type OrderItem struct {

	// The ID of the product
	ProductId int32 `json:"product_id,omitempty"`

	// The quantity of the product
	Quantity int32 `json:"quantity,omitempty"`

	// The price of the product
	Price float32 `json:"price,omitempty"`

	// The VAT of the product
	Vat float32 `json:"vat,omitempty"`
}

// AssertOrderItemRequired checks if the required fields are not zero-ed
func AssertOrderItemRequired(obj OrderItem) error {
	return nil
}

// AssertOrderItemConstraints checks if the values respects the defined constraints
func AssertOrderItemConstraints(obj OrderItem) error {
	return nil
}
