// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Purchase Cart API
 *
 * Purchase Cart API is an API to create an order with items and get the pricing information for the order
 *
 * API version: 1.0
 */

package api

// CreateOrderRequestOrder - The order payload to create an order
type CreateOrderRequestOrder struct {

	// The items to purchase
	Items []CreateOrderRequestOrderItemsInner `json:"items"`
}

// AssertCreateOrderRequestOrderRequired checks if the required fields are not zero-ed
func AssertCreateOrderRequestOrderRequired(obj CreateOrderRequestOrder) error {
	elements := map[string]interface{}{
		"items": obj.Items,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Items {
		if err := AssertCreateOrderRequestOrderItemsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertCreateOrderRequestOrderConstraints checks if the values respects the defined constraints
func AssertCreateOrderRequestOrderConstraints(obj CreateOrderRequestOrder) error {
	for _, el := range obj.Items {
		if err := AssertCreateOrderRequestOrderItemsInnerConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
