// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Purchase Cart API
 *
 * Purchase Cart API is an API to create an order with items and get the pricing information for the order
 *
 * API version: 1.0
 */

package api

type CreateOrderRequestOrderItemsInner struct {
	ProductId int32 `json:"product_id"`

	Quantity int32 `json:"quantity"`
}

// AssertCreateOrderRequestOrderItemsInnerRequired checks if the required fields are not zero-ed
func AssertCreateOrderRequestOrderItemsInnerRequired(obj CreateOrderRequestOrderItemsInner) error {
	elements := map[string]interface{}{
		"product_id": obj.ProductId,
		"quantity":   obj.Quantity,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateOrderRequestOrderItemsInnerConstraints checks if the values respects the defined constraints
func AssertCreateOrderRequestOrderItemsInnerConstraints(obj CreateOrderRequestOrderItemsInner) error {
	return nil
}
