name: purchase-cart
services:
  mytest:
    build:
      context: ../
    volumes:
      - ..:/mnt
      - ~/go/pkg:/go/pkg # TODO: remove
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9090:9090"
    working_dir: /mnt

  mongo:
    image: mongo:4.4
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017" # TODO: remove
